# Generated by Django 5.1.15 on 2026-02-01 23:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carte',
            field=wagtail.fields.StreamField([('card_section', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the heading will be hidden from view and avaliable to screen-readers only.', 'label': 'Screen reader only label', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('page', 4), ('title', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('link', 7), ('title', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('internal', 6), ('external', 9)]], {'min_num': 0, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('heading', 2), ('description', 3), ('link', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Card', 'max_num': 6, 'min_num': 3}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('sr_only_label', 1), ('cards', 12)]], {})}),
        ),
    ]
